version: "3.2"

services:
    elasticsearch:
        container_name: sample-elasticsearch
        image: elasticsearch:7.13.1
        volumes:
          - type: bind
            source: "${PWD}/elk/elasticsearch/config/elasticsearch.yml"
            target: /usr/share/elasticsearch/config/elasticsearch.yml
            read_only: true
            #- "${PWD}/elk/elasticsearch/data:/usr/share/elasticsearch/data:rw"
        ports:
          - "9200:9200"
          #- "9300:9300"
        environment:
          ES_JAVA_OPTS: "-Xmx4096m -Xms4096m"
          ## Use single node discovery in order to disable production mode and avoid bootstrap checks
          ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
          discovery.type: single-node
        #ulimits:
        #  memlock:
        #    soft: -1
        #    hard: -1
        networks:
          - efk
        restart: always
    
      kibana:
        container_name: sample-kibana
        image: kibana:7.13.1
        volumes:
          - type: bind
            source: "${PWD}/elk/kibana/config/kibana.yml"
            target: /usr/share/kibana/config/kibana.yml
            read_only: true
        ports:
          - "5601:5601"
        networks:
          - efk
        restart: always
        depends_on:
          - elasticsearch

    fluentd:
        # image: fluent/fluentd:v1.13
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sample_fluentd
        volumes:
            - type: bind
              source: "${PWD}/etc/fluent.conf"
              target: /fluentd/etc/fluent.conf
              read_only: true
        command: ["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
        ports:
            # - "5140:5140"
            - "24224:24224"
        networks:
            - efk
        restart: always
        depends_on:
            - elasticsearch

    fluentbit:
        image: fluent/fluent-bit:1.7.9-debug
        container_name: sample_fluentbit
        volumes:
            - type: bind
              source: ${PWD}/etc/fluent-bit.conf
              target: /fluent-bit/etc/fluent-bit.conf
              read_only: true
        ports:
            # - "2020:2020"
            - "9880:9880"
        networks:
            - efk
        restart: always
        depends_on:
            - fluentd

networks:
    efk:
        driver: bridge

